const ar_f = [
  {"F": "https://i.imgur.com/7CeC4ln.jpg", "N": "أفغانستان"},
  {"F": "https://i.imgur.com/1mbQUjL.jpg", "N": "البانيا"},
  {"F": "https://i.imgur.com/QAqpW8G.jpg", "N": "أندورا"},
  {"F": "https://i.imgur.com/WJW4Zk8.jpg", "N": "أنغولا"},
  {"F": "https://i.imgur.com/xzQOd6W.jpg", "N": "الأرجنتين"},
  {"F": "https://i.imgur.com/WxxWfcr.jpg", "N": "أرمينيا"},
  {"F": "https://i.imgur.com/VtTdNbK.jpg", "N": "أستراليا"},
  {"F": "https://i.imgur.com/KWyo2ZL.png", "N": "الدانمارك"},
  {"F": "https://i.imgur.com/FUbDjrN.png", "N": "كندا"},
  {"F": "https://i.imgur.com/agdbPcW.png", "N": "الصين"},
  {"F": "https://i.imgur.com/aqq9XM1.jpg", "N": "سوريا"},
  {"F": "https://i.imgur.com/zGYoHGZ.jpg", "N": "تونس"},
  {"F": "https://i.imgur.com/to6oeFz.png", "N": "كرواتيا"},
  {"F": "https://i.imgur.com/qdJtWSj.gif", "N": "كولومبيا"},
  {"F": "https://i.imgur.com/ZxBJedi.gif", "N": "فنلندا"},
  {"F": "https://i.imgur.com/F1MtuqQ.gif", "N": "ألمانيا"},
  {"F": "https://i.imgur.com/4yBqewj.gif", "N": "اليونان"},
  {"F": "https://i.imgur.com/bEfgbGl.gif", "N": "أيسلندا"},
  {"F": "https://i.imgur.com/XC25B1r.gif", "N": "المجر"},
  {"F": "https://i.imgur.com/kCLQfaE.gif", "N": "اليابان"},
  {"F": "https://i.imgur.com/ygd5UjF.gif", "N": "لاتفيا"},
  {"F": "https://i.imgur.com/VQlqRWV.gif", "N": "كازاخستان"},
  {"F": "https://i.imgur.com/WDfhiBm.gif", "N": "ماليزيا"},
  {"F": "https://i.imgur.com/UooMhFU.gif", "N": "لوكسمبورغ"},
  {"F": "https://i.imgur.com/YgOBBMT.gif", "N": "مالطا"},
  {"F": "https://i.imgur.com/7ie3cJW.gif", "N": "المكسيك"},
  {"F": "https://i.imgur.com/my09qW6.gif", "N": "مولدوفا"},
  {"F": "https://i.imgur.com/9tJKPLl.gif", "N": "أرمينيا"},
  {"F": "https://i.imgur.com/B1vB6Dt.gif", "N": "النمسا"},
  {"F": "https://i.imgur.com/XRf2j5n.gif", "N": "أذربيجان"},
  {"F": "https://i.imgur.com/hCuycp6.gif", "N": "بنغلاديش"},
  {"F": "https://i.imgur.com/QSbdwru.gif", "N": "بلجيكا"},
  {"F": "https://i.imgur.com/KhztKKk.gif", "N": "بوليفيا"},
  {"F": "https://i.imgur.com/5M3vUO9.gif", "N": "البرازيل"},
  {"F": "https://i.imgur.com/XxwktPF.gif", "N": "ساحل العاج"},
  {"F": "https://i.imgur.com/nsmhYXF.gif", "N": "الكاميرون"},
  {"F": "https://i.imgur.com/dRCZjUX.gif", "N": "جمهورية الدومينيكان"},
  {"F": "https://i.imgur.com/tVwdyDz.gif", "N": "الإكوادور"},
  {"F": "https://i.imgur.com/nlF5aoq.gif", "N": "بلغاريا"},
  {"F": "https://i.imgur.com/WODDJ55.gif", "N": "السلفادور"},
  {"F": "https://i.imgur.com/9Dknt44.jpg", "N": "الإمارات"},
  {"F": "https://i.imgur.com/v0BSSjx.jpg", "N": "اليمن"},
  {"F": "https://i.imgur.com/tTzA2r6.jpg", "N": "المملكة العربية السعودية"},
  {"F": "https://i.imgur.com/RR704H2.jpg", "N": "الصومال"},
  {"F": "https://i.imgur.com/Px1pTYk.jpg", "N": "السودان"},
  {"F": "https://i.imgur.com/SgjhHTO.jpg", "N": "عمان"},
  {"F": "https://i.imgur.com/vRMMHRH.jpg", "N": "فلسطين"},
  {"F": "https://i.imgur.com/L0WfyBv.gif", "N": "إستونيا"},
  {"F": "https://i.imgur.com/OiJFDnP.jpg", "N": "قطر"},
  {"F": "https://i.imgur.com/Uf19Plt.jpg", "N": "مصر"},
  {"F": "https://i.imgur.com/8xq7z1n.jpg", "N": "ليبيا"},
  {"F": "https://i.imgur.com/iixfx2D.jpg", "N": "موريتانيا"},
  {"F": "https://i.imgur.com/L1NvD1F.jpg", "N": "المغرب"},
  {"F": "https://i.imgur.com/8RV6H2r.jpg", "N": "لبنان"},
  {"F": "https://i.imgur.com/WCklIWW.jpg", "N": "جزر القمر"},
  {"F": "https://i.imgur.com/sm2SZyR.jpg", "N": "الكويت"},
  {"F": "https://i.imgur.com/rbKoQbN.jpg", "N": "العراق"},
  {"F": "https://i.imgur.com/6g7u9mK.jpg", "N": "الأردن"},
  {"F": "https://i.imgur.com/ijep6Tu.jpg", "N": "البحرين"},
  {"F": "https://i.imgur.com/U4q5vn8.jpg", "N": "الجزائر"},
  {"F": "https://i.imgur.com/3pxwh1W.jpg", "N": "إسبانيا"},
  {"F": "https://i.imgur.com/TtEC7ZD.jpg", "N": "البرتغال"}
];

module.exports = { ar_f };